### ISSUE TITLE
Fix deprecation warnings for Symfony 6.1 commands

### ISSUE THREAD

**Issue by tacman** [Guikingone/SchedulerBundle#279] opened 2022-06-10 11:08 UTC
There are a handful of deprecation errors when following the instructions above using php 8.1, because symfony new will install Symfony 6.1 if the php version is 8.1.  

```bash
# make sure php is at least 8.1
php -v 
symfony new scheduler_demo --webapp && cd scheduler_demo
composer require guikingone/scheduler-bundle
bin/console cache:clear
echo "scheduler_bundle: { transport: { dsn: 'filesystem://first_in_first_out' } }" > config/packages/scheduler.yaml
bin/console scheduler:list
```

Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. 

I can fix these and submit a PR.

**Comment by Guikingone** [comment] 2022-06-10 11:23
Hi @tacman 👋🏻 

The issue is already solved / merged in `main`: https://github.com/Guikingone/SchedulerBundle/commit/a116655db2d64e124a302f159f1879f352a6a57d, `0.9.4` should be release pretty soon 🙂

**Comment by tacman** [comment] 2022-06-10 11:29
Hmm, that looks like a different issue (lazy loaded commands), though related.  Isn't the "preferred" way to register commands now via attributes, e.g.

```php
#[AsCommand(
    name: 'scheduler:list',
    description: 'List the tasks',
)]
final class ListTasksCommand extends Command
```

and then remove the ->setName() and ->setDescription() lines.

**Comment by Guikingone** [comment] 2022-06-10 11:31
We could use attributes to define commands in the bundle, feel free to submit an PR to do it 🙂

**Comment by tacman** [comment] 2022-06-10 12:21
OK.  I was hoping rector would have a rule for this already, but  alas, no.

Can you give me some guidance on the non-coding part of submitting a PR?
That is, I assume I should create an issue, then create a branch to resolve
that issue.  Should that branch be from 'main'?  Or 9.4? Or...?

**Comment by Guikingone** [comment] 2022-06-10 12:23
The branch should be created from `main`, the coding standard are set via PHP-CS-Fixer and the "compliance" with PHP 8.0 is fixed via Rector, the CI should easily tell us if the PR is not valid 🙂

**Closed** 2022-06-10 16:07 UTC
Labels: PHP, Improvement
