### ISSUE TITLE
FIFO sort

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#93] opened 2021-05-03 18:58 UTC
Seems that #75 doesn't fix the FIFO sort 😢 

<img width="1217" alt="Capture d’écran 2021-05-03 à 20 55 25" src="https://user-images.githubusercontent.com/21243943/116919699-edfc5e80-ac51-11eb-9b44-be9874913288.png">

```yaml
scheduler_bundle:
  transport:
    dsn: 'doctrine://default?execution_mode=first_in_first_out'
  tasks:
    foo:
      type: 'command'
      command: 'app:foo'
      description: 'foo placeholder task'
      output: true
      single_run: true
    bar:
      type: 'command'
      command: 'app:bar'
      description: 'foo placeholder task'
      output: true
      single_run: true
```

expected `foo` then `bar` right ?

**Comment by Guikingone** [comment] 2021-05-03 19:49
Hi @jvancoillie 👋🏻 

You're right, I found the reason of this weird output: 

```php
try {
            return $this->driverConnection->transactional(function (): TaskListInterface {
                $query = $this->createQueryBuilder()->orderBy('task_name', Criteria::ASC);

                $statement = $this->executeQuery($query->getSQL());
                $tasks = $statement->fetchAllAssociative();

                return new TaskList($this->schedulePolicyOrchestrator->sort(
                    $this->configuration['execution_mode'],
                    array_map(fn (array $task): TaskInterface => $this->serializer->deserialize($task['body'], TaskInterface::class, 'json'), $tasks)
                ));
            });
        } catch (Throwable $throwable) {
            throw new TransportException($throwable->getMessage(), $throwable->getCode(), $throwable);
        }
```

The issue is related to the `orderBy()` call, the call must be removed 🙂

**Comment by jvancoillie** [comment] 2021-05-03 21:00
after reflection, sorting was not necessarily a bad thing because I think that the  filesystem transport will recover task list based on the name too and therefore we will return the same problem, right?

**Comment by Guikingone** [comment] 2021-05-04 05:29
> after reflection, sorting was not necessarily a bad thing

Don't get the point here 🤔

**Comment by jvancoillie** [comment] 2021-05-04 05:45
Sorry my english is so bad 😢   
I wanted to say that with the orderby we find the same behavior of retrieving  task list with the filesystem transporter which I think recovers the files in alpha order. In other words, I wonder if the filesystem transport will not return a bad FIFO sort.

**Comment by Guikingone** [comment] 2021-05-04 05:46
I just tested it on the linked PR and it seems that the filesystem transport does not encounter issues when it comes to retrieving tasks and a FIFO sort 🙂

**Comment by Guikingone** [comment] 2021-05-04 05:58
Issue solved via https://github.com/Guikingone/SchedulerBundle/pull/95, planned to be released in `0.4.4` 🙂

**Comment by jvancoillie** [comment] 2021-05-09 09:23
> I just tested it on the linked PR and it seems that the filesystem transport does not encounter issues when it comes to retrieving tasks and a FIFO sort 🙂

I guess this is the test you were talking about 

https://github.com/Guikingone/SchedulerBundle/blob/d4708191754f16a66389a99946ad379ccfe3b4a6/tests/Transport/FilesystemTransportTest.php#L125-L130

while wanting to work on an improvement of the worker, I noticed that the testTaskListCanBeRetrieved failed, FIFO sorting does not work for me (main 0.4.4)

<img width="1452" alt="Capture d’écran 2021-05-09 à 11 21 57" src="https://user-images.githubusercontent.com/21243943/117566741-ca557000-b0b8-11eb-9bd6-8730c96d2b46.png">

**Comment by Guikingone** [comment] 2021-05-09 12:49
@jvancoillie If FIFO sort does not work on your PR, be sure to has rebased against `main`, if the issue still occurs, consider opening a new PR 🙂

**Closed by Guikingone** 2021-05-09 12:49 UTC
Labels: Bridge, PHP, bug
