### ISSUE TITLE
bug(collector): scheduler panel

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#47] opened 2021-03-31 05:37 UTC
Hello it's me again,

I throw an exception when I consult the profiler (_profiler/latest?panel=scheduler) 
<img width="1164" alt="Capture d’écran 2021-03-31 à 07 38 41" src="https://user-images.githubusercontent.com/21243943/113095687-31e3ea00-91f4-11eb-9e94-1904eb7f08bb.png">

after having consulted the HTTP entrypoint _tasks?name=activation. 
maybe it's related to the `single_run` #45 issue 
<img width="1164" alt="Capture d’écran 2021-03-31 à 07 38 55" src="https://user-images.githubusercontent.com/21243943/113095700-39a38e80-91f4-11eb-8895-6e6e3021736a.png">

thank you again for your responsiveness

**Comment by Guikingone** [comment] 2021-03-31 06:13
Hi @jvancoillie 👋🏻 

Yes, can be related as the task has been unscheduled / updated, I'm taking a look at it today 🙂

**Comment by jvancoillie** [comment] 2021-03-31 06:26
@Guikingone A big thanks, I will continue with the configuration of the other tasks. I'll try to leave you alone.

is there a slack channel for this bundle? I sometimes have questions but they are more functional, I would not like to pollute github issue

**Comment by Guikingone** [comment] 2021-03-31 06:28
No problem, if you meet issues, do not hesitate to open issues 🙂 

If you have functional questions, you can use the discussions: https://github.com/Guikingone/SchedulerBundle/discussions

**Comment by Guikingone** [comment] 2021-04-06 09:38
Hi @jvancoillie 👋🏻 

As `0.4` is under pre-release process, I'm gonna investigate this issue before processing the release, I'll let you know if the issue is fixed 🙂

**Comment by Guikingone** [comment] 2021-04-21 08:30
Hi @jvancoillie 👋🏻 

Have you updated your project to `0.4.1`? It seems that the issue is fixed since `0.4`, could you confirm? 🤔

**Comment by jvancoillie** [comment] 2021-04-21 09:19
Hi @Guikingone 

Good news, I will install and check this quickly. I will come back to you.

**Comment by jvancoillie** [comment] 2021-04-21 10:42
I just installed version 0.4.1.

The first run of `bin/console scheduler:consume` (`single_run` with doctrine transport) everything seems to be going correctly.

Then on a second run `bin/console scheduler:consume` or on the HTTP entrypoint `_tasks?name=activation`consultation there seems to be a loop.

This is what I have in the logs. 
```shell
#...
php-fpm_1  | [2021-04-21T10:33:44.549573+00:00] app.INFO: The following task "activation" is paused|disabled, consider enable it if it should be executed! {"name":"activation","expression":"* * * * *","state":"paused"} []
php-fpm_1  | [2021-04-21T10:33:44.549615+00:00] app.INFO: The following task "activation" is paused|disabled, consider enable it if it should be executed! {"name":"activation","expression":"* * * * *","state":"paused"} []
php-fpm_1  | [2021-04-21T10:33:44.549651+00:00] app.INFO: The following task "activation" is paused|disabled, consider enable it if it should be executed! {"name":"activation","expression":"* * * * *","state":"paused"} []
php-fpm_1  | [2021-04-21T10:33:44.549686+00:00] app.INFO: The following task "activation" is paused|disabled, consider enable it if it should be executed! {"name":"activation","expression":"* * * * *","state":"paused"} []
php-fpm_1  | NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/app/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php on line 157
```

**Comment by jvancoillie** [comment] 2021-04-21 15:10
@Guikingone 

I think I identified the infinite loop problem. When a task is `disabled|Paused` the shouldStop property is never set to true. suddenly it loops :( [Worker.php#L107](https://github.com/Guikingone/SchedulerBundle/blob/b4189611deb123f7dcbcc6ffd6eb75f0c22e03c2/src/Worker/Worker.php#L107)

**Comment by Guikingone** [comment] 2021-04-22 06:22
Hum, strange behaviour, I think it's related to `$tasksCount` and not to `$shouldStop`, I'm gonna investigate 🤔

**Comment by Guikingone** [comment] 2021-04-22 06:51
@jvancoillie Could you test this issue via `dev-issue/47` when you have a moment? 

If it's valid, the fix will be released as `0.4.2` 🙂

**Comment by jvancoillie** [comment] 2021-04-22 07:40
Hi @Guikingone 

Juste try the `guikingone/scheduler-bundle dev-issue/47 9087d2f`

I get the same loop with the following configuration:
```yaml
# config/packages/scheduler.yaml
scheduler_bundle:
    transport:
        dsn: 'doctrine://default?execution_mode=first_in_first_out&table_name=scheduler_tasks&auto_setup=false'
    tasks:
        activation:
            type: 'command'
            command: 'app:activation'
            description: 'Test command'
            single_run: true
            output: true
            output_to_store: true
            priority: 1
            tags: ['api']
```

```bash
# reboot
developer@0515af07330c:/var/www/app$ bin/console scheduler:reboot 

 [OK] The scheduler have been rebooted, no tasks have been executed
 
# first call it's all fine
developer@0515af07330c:/var/www/app$  bin/console scheduler:consume

 // Quit the worker with CONTROL-C.

 ! [NOTE] The task output can be displayed if the -vv option is used

 [OK] Task "activation" succeed. (Duration: < 1 sec, Memory used: 40.9 MiB)

# second call falls into an infinite loop 
developer@0515af07330c:/var/www/app$ bin/console scheduler:consume

 // Quit the worker with CONTROL-C.

 ! [NOTE] The task output can be displayed if the -vv option is used

[2021-04-22T07:31:06.705070+00:00] app.INFO: The following task "activation" is paused|disabled, consider enable it if it should be executed! {"name":"activation","expression":"* * * * *","state":"paused"} []
[2021-04-22T07:31:06.705140+00:00] app.INFO: The following task "activation" is paused|disabled, consider enable it if it should be executed! {"name":"activation","expression":"* * * * *","state":"paused"} []
[2021-04-22T07:31:06.705177+00:00] app.INFO: The following task "activation" is paused|disabled, consider enable it if it should be executed! {"name":"activation","expression":"* * * * *","state":"paused"} []
// ...
```

**Comment by jvancoillie** [comment] 2021-04-22 09:31
can check it with this testcase

```php
final class WorkerTest extends TestCase 
{
   /**
     * @throws Throwable
     */
    public function testIssue47(): void
    {
        $logger = $this->createMock(LoggerInterface::class);
        $logger->expects(self::once())->method('info')->with(
            self::equalTo('The following task "foo" is paused|disabled, consider enable it if it should be executed!'),
            [
                'name' => 'foo',
                'expression' => '* * * * *',
                'state' => TaskInterface::PAUSED,
            ]
        );

        $task = $this->createMock(TaskInterface::class);
        $task->expects(self::exactly(3))->method('getName')->willReturn('foo');
        $task->expects(self::once())->method('getExpression')->willReturn('* * * * *');
        $task->expects(self::exactly(3))->method('getState')->willReturn(TaskInterface::PAUSED);

        $tracker = $this->createMock(TaskExecutionTrackerInterface::class);
        $runner = $this->createMock(RunnerInterface::class);


        $scheduler = $this->createMock(SchedulerInterface::class);
        $scheduler->expects(self::never())->method('getTimezone');
        $scheduler->expects(self::once())->method('getDueTasks')->willReturn(new TaskList([$task]));

        $eventDispatcher = new EventDispatcher();
        $eventDispatcher->addSubscriber(new StopWorkerOnTaskLimitSubscriber(1));

        $worker = new Worker($scheduler, [$runner], $tracker, new WorkerMiddlewareStack([
            new SingleRunTaskMiddleware($scheduler),
            new TaskUpdateMiddleware($scheduler),
        ]), $eventDispatcher, $logger);
        $worker->execute();
        
    }
}
```

 throws the following
 SchedulerBundle\Task\TaskInterface::getState(): string was not expected to be called more than 3 times.
    
it means that `excute()` function loop on this unique task

**Comment by Guikingone** [comment] 2021-04-22 09:59
Hum, I'm starting to think that maybe, the worker logic can be changed as we probably don't need to retrieved tasks that are paused / disabled 🤔

**Comment by Guikingone** [comment] 2021-04-22 11:23
Hum, I've investigated during lunch and the issue is really weird for multiple reasons:

- A paused / disabled task is not executed but continues to exist in the `$tasks` loop if the task is defined as "due": https://github.com/Guikingone/SchedulerBundle/blob/b4189611deb123f7dcbcc6ffd6eb75f0c22e03c2/src/Worker/Worker.php#L102.

- A paused / disabled task cannot increment the task count as we don't execute it. 

- The worker continues to loop over the tasks as it's not stopped (thanks to `$shouldStop`) AND tries to execute the paused / disabled tasks (as each is marked as due). 

Regarding these facts, there's 2 major options: 

- Filtering the tasks before looping over it and trying to execute only the ones which are enabled

- Checking the current pointer position and doing something like this:

```bash
If the current task is the last one and a "paused / disabled" one
Then stop the worker
```

By `stop the worker`, I mean that we can check this situation here: https://github.com/Guikingone/SchedulerBundle/blob/b4189611deb123f7dcbcc6ffd6eb75f0c22e03c2/src/Worker/Worker.php#L151. 

Any thoughts? 🤔 

PS: @jmsche If you have an opinion, i'll be glad to ear it 🙂

**Comment by Guikingone** [comment] 2021-04-26 09:01
Hi @jvancoillie 👋🏻 

I've pushed a new version of the fix, could you test it when you have a moment? 

Thanks and sorry for the delay 🙂

**Comment by jvancoillie** [comment] 2021-04-26 10:41
Hi @Guikingone,

Thanks, I will test this after my lunch break.

**Comment by jvancoillie** [comment] 2021-04-26 11:48
﻿@Guikingone 

Juste tested, it works fine when I only have one `single_run` task. As I feared it loops when multiple tasks are disabled or paused

**Comment by Guikingone** [comment] 2021-04-26 11:58
Yes, just updated the PR 🙂

**Comment by jvancoillie** [comment] 2021-04-26 12:05
Great, it works ! 
<img width="847" alt="Capture d’écran 2021-04-26 à 14 04 35" src="https://user-images.githubusercontent.com/21243943/116079671-62eef780-a698-11eb-97c4-bb11a5c48052.png">

**Comment by Guikingone** [comment] 2021-04-26 12:08
Great news, I'm gonna fix the CI of the PR and merge it, must be released in `0.4.2` 🙂

**Comment by jvancoillie** [comment] 2021-04-26 12:16
I wanted to validate that this also corrects the bug on the scheduler panel.

I have an error when consulting the task via the HTTP entrypoint :( 
```json
{
   "code":500,
   "message":"Argument 1 passed to iterator_to_array() must implement interface Traversable, array given",
   "trace":"#0 \/var\/www\/app\/vendor\/guikingone\/scheduler-bundle\/src\/Worker\/Worker.php(107): iterator_to_array(Array)\n#1 \/var\/www\/app\/vendor\/guikingone\/scheduler-bundle\/src\/EventListener\/TaskSubscriber.php(84): SchedulerBundle\\Worker\\Worker-\u003Eexecute(Array, Object(SchedulerBundle\\Task\\CommandTask))\n#2 \/var\/www\/app\/vendor\/symfony\/event-dispatcher\/Debug\/WrappedListener.php(117): SchedulerBundle\\EventListener\\TaskSubscriber-\u003EonKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\RequestEvent), \u0027kernel.request\u0027, Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#3 \/var\/www\/app\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php(230): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener-\u003E__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\RequestEvent), \u0027kernel.request\u0027, Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))\n#4 \/var\/www\/app\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php(59): Symfony\\Component\\EventDispatcher\\EventDispatcher-\u003EcallListeners(Array, \u0027kernel.request\u0027, Object(Symfony\\Component\\HttpKernel\\Event\\RequestEvent))\n#5 \/var\/www\/app\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php(151): Symfony\\Component\\EventDispatcher\\EventDispatcher-\u003Edispatch(Object(Symfony\\Component\\HttpKernel\\Event\\RequestEvent), \u0027kernel.request\u0027)\n#6 \/var\/www\/app\/vendor\/symfony\/http-kernel\/HttpKernel.php(133): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher-\u003Edispatch(Object(Symfony\\Component\\HttpKernel\\Event\\RequestEvent), \u0027kernel.request\u0027)\n#7 \/var\/www\/app\/vendor\/symfony\/http-kernel\/HttpKernel.php(79): Symfony\\Component\\HttpKernel\\HttpKernel-\u003EhandleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#8 \/var\/www\/app\/vendor\/symfony\/http-kernel\/Kernel.php(195): Symfony\\Component\\HttpKernel\\HttpKernel-\u003Ehandle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#9 \/var\/www\/app\/public\/index.php(20): Symfony\\Component\\HttpKernel\\Kernel-\u003Ehandle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#10 {main}"
}
```

**Comment by Guikingone** [comment] 2021-04-26 12:17
Yes, fixed locally, I've added a check on the variable passed to `iterator_to_array` 🙂

**Comment by jvancoillie** [comment] 2021-04-26 12:19
Very good ! Sorry for the inconvenience ;)

**Comment by Guikingone** [comment] 2021-04-26 16:18
Small question about this fix @jvancoillie, does it solve the scheduler panel one? 🤔

**Comment by jvancoillie** [comment] 2021-04-26 16:42
yes @Guikingone it seems to be fixed, the profiler `_profiler/latest?panel=scheduler` no longer throws an exception 👍

**Comment by Guikingone** [comment] 2021-04-26 16:47
Ok, PR to merge, `0.4.2` must be released tonight 🙂

**Closed** 2021-04-26 16:47 UTC
Labels: PHP, bug
